sudo: required
language: c
git:
  depth: 4
os:
- linux
- osx
matrix:
  allow_failures:
  - os: osx
env:
  linux_dist: ubuntu
  linux_ver: 16.04
  linux_init: "/lib/systemd/systemd"
  linux_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
services:
- docker
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo docker pull ${linux_dist}:${linux_ver}
  ; fi
script:
- build/travis/store-travis-info
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then container_id_file=$(mktemp) ; export
  container_id_file ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo docker run --detach --volume="${PWD}":/srv/git:rw
  ${linux_opts} ${linux_dist}:${linux_ver} "${linux_init}" > "${container_id_file}"
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo docker exec --tty "$(cat ${container_id_file})"
  /srv/git/build/travis/install.linux  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then build/travis/install.osx ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo docker stop "$(cat ${container_id_file})"
  ; fi
deploy:
  provider: bintray
  user: lgblgblgb
  file: build/deploy/bintray-description.json
  on: deploy
  key:
    secure: TY/iIWMbyY3ZO3kAkhXgSDCAig13TBH4O7nF06P1d+3xdOKrpP1DiMo3YsHnDs6tNVCiAoBFQQaFiyGPGQGzMZ5aTq6B4qs7VVvHQg+ghx2z6aMn1OWls+iHPfTaTDBku7XR5o6wmSRcGfRhgE2hAcizHQEzHvBiyYiQ0OGqvXDjtCw/bWO4inpb4IEEQY7EuGdUllLQ6I7ma+eGihhAb21acZ4mGsZyqYgqTZ/QqYpc1inTU3tsC112bhp138k3HslDdmxQuJGxUJv+sF1SyNBiRBKfdRCVob+C12yJ18Iy1gVUqYtpoW5bJi+s0tclD5sK5AyA6FVoVkrrH42U1ZWA/TWYzw1+XkGTdhmh2wHFvAZRuPESVJBBaOpzo12kjdDnhvttbnX0Ii4N5fQCAwsVFt9Oof7opXtk9TUATSzfOHNxlE5p8XydQ5oZM3apqu+Cih6J/RK0IQPgnGaKZzLVPPsUuyyCTtobmfNchGKTjeqpRumvvxmUrE1FSZSUaKr6a//vuZgUs49HvWDLwP+bgX+ChCjJFLJLowWbOd4gTZ41I/vc4ErIXrTWD6xtbP/h3vjTFLy/FFWfelR46r4OkWC2ALFJfl3K/RRSY+qU8V0PU8WqjSzO6E4NkpYi0s+lN23xVRIRKVP6E5RilI/3fdLNzZuMI66h4Z8SOKA=
