#!/bin/bash

VERSION="`sed -nr 's/^#[\t ]*define[\t ]+VERSION[\t ]+"([^"]*).*$/\1/p' xep128.h`+`date '+%Y%m%d%H%M%S'`"

rm -fr .dist
mkdir -p .dist/xep128_$VERSION/usr/local/bin .dist/xep128_$VERSION/usr/local/lib/xep128 .dist/xep128_$VERSION/DEBIAN || exit 1
cp xep128 .dist/xep128_$VERSION/usr/local/bin/ || exit 1
strip .dist/xep128_$VERSION/usr/local/bin/xep128

echo "Package: xep128
Version: $VERSION
Section: base
Priority: optional
Architecture: amd64
Depends: libsdl2-2.0-0 (>= 2.0.4), libreadline6 (>= 6.3), libgtk-3-0 (>= 3.18), libc6 (>= 2.15)
Maintainer: Gábor Lénárt <lgblgblgb@gmail.com>
Description: Enterprise-128 software emulator
 Enterprise-128 is a Z80 based "home computer" released in 1984. This emulator
 uses SDL2 and tries to emulate it especially focusing on "exotic" hardware add-ons,
 including "modern" ones (ie: SD card reader). Z80 emulation is done with (modified)
 Z80ex CPU emulator.
Homepage: http://xep128.lgb.hu/" > .dist/xep128_$VERSION/DEBIAN/control

echo "#!/bin/sh
if [ ! -s /usr/local/lib/xep128/combined.rom ]; then
	rm -f /usr/local/lib/xep128/combined.rom
	wget -O /usr/local/lib/xep128/combined.rom http://xep128.lgb.hu/files/combined.rom || { rm -f /usr/local/lib/xep128/combined.rom ; exit 1; }
fi
exit 0" > .dist/xep128_$VERSION/usr/local/bin/xep128-download-data

find .dist/xep128_$VERSION -type d -exec chmod u-s,g-s,g-w,o-w,u+rwx,g+rx,o+rx {} \;
find .dist/xep128_$VERSION -type f -exec chmod 0644 {} \;
chmod 0755 .dist/xep128_$VERSION/usr/local/bin/xep128 .dist/xep128_$VERSION/usr/local/bin/xep128-download-data
touch .dist/xep128_$VERSION/usr/local/lib/xep128/.placeholder

fakeroot dpkg-deb --build .dist/xep128_$VERSION || exit 1

mv .dist/xep128_$VERSION.deb . || exit 1

rm -fr .dist

ls -l xep128_$VERSION.deb

exit 0
